#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
  path: /api/login_check

putusers:
  path: /api/admin/users/{id}
  controller: App\Controller\UserController::UpdateUser
